enable-magisk-update = false
parallel-jobs = 1
compression-level = 9
riplib = true

[Music-Extended]
enabled = false
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
patches-version = "latest"
app-name = "Music"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube Music' \
    'Custom branding icon for YouTube Music' \
    """

[YouTube-Extended]
enabled = false
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "latest"
app-name = "YouTube"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube' \
    'Custom branding icon for YouTube' \
    """

[Music-Extended-dev]
enabled = false
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "dev"
app-name = "Music"
rv-brand = "ReVanced Extended-dev"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube Music' \
    'Custom branding icon for YouTube Music' \
    """

[YouTube-Extended-dev]
enabled = false
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "dev"
app-name = "YouTube"
rv-brand = "ReVanced Extended-dev"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube' \
    'Custom branding icon for YouTube' \
    """

[anddea-Music-Extended]
enabled = false
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "latest"
app-name = "Music"
rv-brand = "ReVanced Anddea"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube Music' \
    'Custom branding icon for YouTube Music' \
    """

[anddea-YouTube-Extended]
enabled = false
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "latest"
app-name = "YouTube"
rv-brand = "ReVanced Anddea"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube' \
    'Custom branding icon for YouTube' \
    """

[anddea-Music-Extended-dev]
enabled = false
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "dev"
app-name = "Music"
rv-brand = "ReVanced Anddea-dev"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube Music' \
    'Custom branding icon for YouTube Music' \
    """

[anddea-YouTube-Extended-dev]
enabled = false
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "dev"
app-name = "YouTube"
rv-brand = "ReVanced Anddea-dev"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube' \
    'Custom branding icon for YouTube' \
    """

[Morphe-Music]
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
app-name = "Music"
cli-version = "dev"
rv-brand = "Morphe"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
github-release-dlurl = "https://github.com/AzyrRuthless/YTYTM-APK/releases/latest"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
included-patches = ""
excluded-patches = """\
    'Custom branding' \
    """

[Morphe-YouTube]
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
app-name = "YouTube"
cli-version = "dev"
rv-brand = "Morphe"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
github-release-dlurl = "https://github.com/AzyrRuthless/YTYTM-APK/releases/latest"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = ""
excluded-patches = """\
    'Custom branding' \
    """

[Morphe-Music-dev]
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = """'v1.13.0-dev.10'"""
app-name = "Music"
cli-version = "dev"
rv-brand = "Morphe-dev"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
github-release-dlurl = "https://github.com/AzyrRuthless/YTYTM-APK/releases/latest"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
included-patches = ""
excluded-patches = """\
    'Custom branding' \
    """

[Morphe-YouTube-dev]
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = """'v1.13.0-dev.10'"""
app-name = "YouTube"
cli-version = "dev"
rv-brand = "Morphe-dev"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
github-release-dlurl = "https://github.com/AzyrRuthless/YTYTM-APK/releases/latest"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = ""
excluded-patches = """\
    'Custom branding' \
    """
