enable-module-update = false
parallel-jobs = 1
compression-level = 9
remove-rv-integrations-checks = false

[Music-Morphe]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "dev"
rv-brand = "Morphe"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
direct-dlurl = "https://github.com/steven7851/revanced-magisk-module/releases/download/1/com.google.android.apps.youtube.music-8.47.56-arm64-v8a.apk"
arch = "arm64-v8a"
patcher-args = ""
included-patches = ""
excluded-patches = """\
    'Custom branding' \
    """

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "dev"
rv-brand = "Morphe"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
direct-dlurl = "https://github.com/steven7851/revanced-magisk-module/releases/download/1/com.google.android.youtube-20.47.62-all.apk"
arch = "all"
patcher-args = """\
    --striplibs arm64-v8a \
    """
included-patches = ""
excluded-patches = """\
    'Custom branding' \
    """

[Music-Morphe-dev]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "dev"
rv-brand = "Morphe-dev"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
direct-dlurl = "https://github.com/steven7851/revanced-magisk-module/releases/download/1/com.google.android.apps.youtube.music-8.47.56-arm64-v8a.apk"
arch = "arm64-v8a"
patcher-args = ""
included-patches = ""
excluded-patches = """\
    'Custom branding' \
    """

[YouTube-Morphe-dev]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "dev"
rv-brand = "Morphe-dev"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
direct-dlurl = "https://github.com/steven7851/revanced-magisk-module/releases/download/1/com.google.android.youtube-20.47.62-all.apk"
arch = "all"
patcher-args = """\
    --striplibs arm64-v8a \
    """
included-patches = ""
excluded-patches = """\
    'Custom branding' \
    """
