logging-to-file = false        # enables logging of every patch process to a seperate file
enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music-Extended]
enabled = false
app-name = "Music"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"
version = "auto"
included-patches = ""
excluded-patches = ""

[YouTube-Extended]
app-name = "YouTube"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
version = "auto"
included-patches = "'Disable landscape mode' 'Hide double tap overlay filter' 'Enable music search' 'Hide voice search button'"
excluded-patches = "'Custom branding name YouTube' 'Custom branding icon YouTube' 'MaterialYou'"
